ARG CANN_VERSION=9.0.0
ARG DEVICE_TYPE=a3
ARG OS=ubuntu22.04
ARG PYTHON_VERSION=py3.11

FROM quay.io/ascend/cann:$CANN_VERSION-$DEVICE_TYPE-$OS-$PYTHON_VERSION

ENV http_proxy http://p_atlas:proxy%40123@90.255.193.253:8080
ENV https_proxy http://p_atlas:proxy%40123@90.255.193.253:8080

# Update pip & apt sources
ARG TARGETARCH="arm64"
ARG CANN_VERSION
ARG DEVICE_TYPE
ARG PIP_INDEX_URL="https://pypi.org/simple/"
ARG APTMIRROR=""
ARG PYTORCH_VERSION="2.10.0"
ARG TORCHVISION_VERSION="0.25.0"
ARG TORCHAUDIO_VERSION="2.10.0"
ARG PTA_URL_ARM64="https://gitcode.com/Ascend/pytorch/releases/download/v26.0.0-pytorch2.10.0/torch_npu-2.10.0-cp311-cp311-manylinux_2_28_aarch64.whl"
ARG PTA_URL_AMD64="https://gitcode.com/Ascend/pytorch/releases/download/v26.0.0-pytorch2.10.0/torch_npu-2.10.0-cp311-cp311-manylinux_2_28_x86_64.whl"
ARG SGLANG_TAG=main
ARG ASCEND_CANN_PATH=/usr/local/Ascend/ascend-toolkit
ARG SGLANG_KERNEL_NPU_TAG="2026.7.2"
ARG arch="aarch64"

ARG PIP_INSTALL="python3 -m pip install --no-cache-dir"
ARG DEVICE_TYPE

RUN if [ "$TARGETARCH" = "amd64" ]; then \
      echo "Using x86_64 dependencies"; \
      echo "PTA_URL=$PTA_URL_AMD64" >> /etc/environment_new; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
      echo "Using aarch64 dependencies"; \
      echo "PTA_URL=$PTA_URL_ARM64" >> /etc/environment_new; \
    else \
      echo "Unsupported TARGETARCH: $TARGETARCH"; exit 1; \
    fi

WORKDIR /workspace

COPY . /workspace

# Define environments
ENV DEBIAN_FRONTEND=noninteractive

RUN pip config set global.index-url $PIP_INDEX_URL
RUN git config --global http.sslverify false
RUN if [ -n "$APTMIRROR" ];then sed -i "s|.*.ubuntu.com|$APTMIRROR|g" /etc/apt/sources.list ;fi

# Install development tools and utilities
RUN apt-get update -y && apt upgrade -y && apt-get install -y \
    unzip \
    build-essential \
    cmake \
    vim \
    wget \
    curl \
    net-tools \
    zlib1g-dev \
    lld \
    clang \
    locales \
    ccache \
    openssl \
    libssl-dev \
    pkg-config \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    ca-certificates \
    gawk \
    && rm -rf /var/cache/apt/* \
    && rm -rf /var/lib/apt/lists/* \
    && update-ca-certificates \
    && locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8


### Install MemFabric
RUN ${PIP_INSTALL} memfabric-hybrid==1.0.8

### Install zbal
RUN if [ "$TARGETARCH" = "arm64" ]; then \
      ${PIP_INSTALL} memfabric-zbal==1.1.1; \
    fi

### Install SGLang Model Gateway
RUN ${PIP_INSTALL} sglang-router


### Install PyTorch and PTA
RUN . /etc/environment_new && \
    (${PIP_INSTALL} torch==${PYTORCH_VERSION} torchvision==${TORCHVISION_VERSION} torchaudio==${TORCHAUDIO_VERSION}) \
    && (${PIP_INSTALL} ${PTA_URL})


## Install triton-ascend
RUN (${PIP_INSTALL} pybind11) && \
    (${PIP_INSTALL} triton-ascend==3.2.1.dev20260530 --extra-index-url=https://mirrors.huaweicloud.com/ascend/repos/pypi/nightly --trusted-host triton-ascend.osinfra.cn)

# Install SGLang (editable mode to preserve source and git history)
RUN git clone https://github.com/sgl-project/sglang --branch $SGLANG_TAG /sgl-workspace/sglang && \
    cd /sgl-workspace/sglang/python && git checkout bd3f6a7935 && rm -rf pyproject.toml && mv pyproject_npu.toml pyproject.toml && \
    ${PIP_INSTALL} -v -e .[all_npu]

RUN mkdir cann-custom-ops && \
    cd cann-custom-ops && \
    wget --no-check-certificate https://github.com/sgl-project/sgl-kernel-npu/releases/download/${SGLANG_KERNEL_NPU_TAG}/custom-ops-${SGLANG_KERNEL_NPU_TAG}-torch2.10.0-cann${CANN_VERSION}-${DEVICE_TYPE}-$(arch).zip && \
    wget --no-check-certificate https://github.com/sgl-project/sgl-kernel-npu/releases/download/${SGLANG_KERNEL_NPU_TAG}/ops-transformer-${SGLANG_KERNEL_NPU_TAG}-torch2.10.0-cann${CANN_VERSION}-${DEVICE_TYPE}-$(arch).zip && \
    unzip custom-ops-${SGLANG_KERNEL_NPU_TAG}-torch2.10.0-cann${CANN_VERSION}-${DEVICE_TYPE}-$(arch).zip && \
    unzip ops-transformer-${SGLANG_KERNEL_NPU_TAG}-torch2.10.0-cann${CANN_VERSION}-${DEVICE_TYPE}-$(arch).zip && \
    chmod +x *.run && \
    ./CANN-custom_ops-none-linux.$(arch).run --install-path=/usr/local/Ascend/cann-${CANN_VERSION}/opp && \
    ./cann-ops-transformer-custom_linux-$(arch).run --install-path=/usr/local/Ascend/cann-${CANN_VERSION}/opp && \
    ${PIP_INSTALL} custom_ops-1.0-cp311-cp311-linux_$(arch).whl && \
    cd .. && rm -rf cann-custom-ops

# Install Deep-ep
# pin wheel to 0.45.1 ref: https://github.com/pypa/wheel/issues/662
RUN ${PIP_INSTALL} wheel==0.45.1 pybind11 pyyaml decorator scipy attrs psutil \
    && mkdir sgl-kernel-npu \
    && cd sgl-kernel-npu \
    && wget --no-check-certificate https://github.com/sgl-project/sgl-kernel-npu/releases/download/${SGLANG_KERNEL_NPU_TAG}/sgl-kernel-npu-${SGLANG_KERNEL_NPU_TAG}-torch2.10.0-py311-cann${CANN_VERSION}-${DEVICE_TYPE}-$(arch).zip \
    && unzip sgl-kernel-npu-${SGLANG_KERNEL_NPU_TAG}-torch2.10.0-py311-cann${CANN_VERSION}-${DEVICE_TYPE}-$(arch).zip \
    && ${PIP_INSTALL} deep_ep*.whl sgl_kernel_npu*.whl torch_memory_saver*.whl \
    && cd .. && rm -rf sgl-kernel-npu \
    && cd "$(python3 -m pip show deep-ep | awk '/^Location:/ {print $2}')" && ln -sf deep_ep/deep_ep_cpp*.so

RUN pip install "transferqueue @ git+https://github.com/redai-infra/TransferQueue.git@dcc78f0a021284412921217fde71fea7cb276ffc" --no-deps

RUN git clone https://gitcode.com/ascend/MindSpeed.git /root/MindSpeed && \
    git clone https://github.com/NVIDIA/Megatron-LM.git /root/Megatron-LM && \
    git clone https://gitcode.com/ascend/MindSpeed-Bridge.git /root/MindSpeed-Bridge && \
    git clone https://github.com/NVIDIA-NeMo/Megatron-Bridge.git /root/Megatron-Bridge

RUN cd /root/MindSpeed && git checkout core_r0.16.0 && pip install -r requirements.txt && pip install -e . && \
    cd /root/Megatron-LM && git checkout core_v0.16.1 && pip install -e . --no-build-isolation && \
    cd /root/Megatron-Bridge && git checkout v0.3.1 && \
    cd /root/MindSpeed-Bridge && git checkout 3655c07cbcc9 && pip install -r requirements.txt && bash tools/install_auto.sh

RUN git clone https://github.com/redai-infra/Relax.git --branch main /root/Relax && \
    cd /root/Relax && git checkout e59cd7288

# Patch Megatron-LM, MindSpeed, MindSpeed-Bridge
RUN cd /root/MindSpeed && \
    patch -p1 < /workspace/mindspeed.patch && \
    cd /root/Megatron-Bridge && \
    patch -p1 < /root/Relax/docker/npu_patch/megatron-bridge.patch && \
    cd /root/Megatron-LM && \
    patch -p1 < /root/Relax/docker/npu_patch/megatron.patch && \
    cd /root/MindSpeed-Bridge && \
    patch -p1 < /workspace/mindspeed-bridge.patch && \
    cd /sgl-workspace/sglang && \
    patch -p1 < /workspace/sglang.patch && \
    cd /root/Relax && \
    patch -p1 < /workspace/relax.patch

# Patch torch_memory_saver
RUN sed -i '164a\            torch.npu.empty_cache()' /usr/local/python3.11.15/lib/python3.11/site-packages/torch_memory_saver/entrypoint.py

# Copy MindSpeed-Bridge, Megatron-Bridge into Megatron-LM
RUN cp -r /root/MindSpeed-Bridge/mindspeed_bridge /root/Megatron-LM/ && \
    cp -r /root/Megatron-Bridge/src/megatron/bridge /root/Megatron-LM/megatron/ && \
    cd /root && rm -rf /root/MindSpeed-Bridge && rm -rf /root/Megatron-Bridge 

RUN cd /root/Relax && pip install -e .

RUN ${PIP_INSTALL} ray==2.55.1 protobuf==6.33.6 torch==${PYTORCH_VERSION} torchvision==${TORCHVISION_VERSION} transformers==5.12.1

RUN cd /root && \
    wget --no-check-certificate https://gitcode.com/Ascend/pytorch/releases/download/v26.0.1-pytorch2.10.0/torch_npu-2.10.0.post2-cp311-cp311-manylinux_2_28_aarch64.whl && \
    pip install torch_npu-2.10.0.post2-cp311-cp311-manylinux_2_28_aarch64.whl && rm torch_npu-2.10.0.post2-cp311-cp311-manylinux_2_28_aarch64.whl

RUN cd /root && \
    mkdir tmp

#  && \    sed -i '1883c\}' build.sh && \
# SHELL ["/bin/bash", "-c"]
RUN source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    git clone https://github.com/flashserve/flash-linear-attention-npu.git /root/flash-linear-attention-npu && \
    cd /root/flash-linear-attention-npu/ && \
    git checkout v26.6.0 && \
    FLA_NPU_SOC=ascend910_93 python -m pip wheel --no-build-isolation --no-deps . -w dist && \
    python -m pip install --force-reinstall --no-deps dist/flash_linear_attention_npu-*.whl

CMD ["/bin/bash"]
